import hero from "/assets/images/hero.jpeg";

export const heroImg = hero;

import hmv from "/assets/videos/hero.mp4";
import smallmv from "/assets/videos/smallHero.mp4";
import highlightFirstmv from "/assets/videos/highlight-first.mp4";
import highlightSectmv from "/assets/videos/hightlight-third.mp4";
import highlightThirdmv from "/assets/videos/hightlight-sec.mp4";
import highlightFourthmv from "/assets/videos/hightlight-fourth.mp4";
import exploremv from "/assets/videos/explore.mp4";
import framemv from "/assets/videos/frame.mp4";
import telephotomv from "/assets/videos/telephoto.mp4";
import foundation from "/assets/videos/foundation.mp4";

import apple from "/assets/images/apple.svg";
import search from "/assets/images/search.svg";
import bag from "/assets/images/bag.svg";
import watchIcon from "/assets/images/watch.svg";
import right from "/assets/images/right.svg";
import replay from "/assets/images/replay.svg";
import play from "/assets/images/play.svg";
import pause from "/assets/images/pause.svg";
import plus from "/assets/images/plus.svg";
import arrowLeft from "/assets/images/arrow-left.svg";
import arrowRight from "/assets/images/arrow-right.svg";
import arrowUp from "/assets/images/arrow-up.svg";
import arrowDown from "/assets/images/arrow-down.svg";

import yellow from "/assets/images/yellow.jpg";
import blue from "/assets/images/blue.jpg";
import white from "/assets/images/white.jpg";
import black from "/assets/images/black.jpg";
import explore1 from "/assets/images/explore1.jpg";
import explore2 from "/assets/images/explore2.jpg";
import chip from "/assets/images/chip.jpeg";
import frame from "/assets/images/frame.png";
import iguana from "/assets/images/iguana.jpg";
import macro from "/assets/images/macro.jpg";
import mm13 from "/assets/images/13mm.jpg";
import mm24 from "/assets/images/24mm.jpg";
import mm28 from "/assets/images/28mm.jpg";
import mm35 from "/assets/images/35mm.jpg";
import mm48 from "/assets/images/48mm.jpg";
import mm120 from "/assets/images/120mm.jpg";
import phoneCamera from "/assets/images/phone-camera.jpg";
import iphonBackground from "/assets/images/iphone-background.png";
import silent from "/assets/images/silent.jpg";
import focus from "/assets/images/focus.jpg";
import camera from "/assets/images/camera.jpg";
import flashlight from "/assets/images/flashlight.jpg";
import voiceMemo from "/assets/images/voice-memo.jpg";
import translate from "/assets/images/translate.jpg";
import magnifier from "/assets/images/magnifier.jpg";
import shortcut from "/assets/images/shortcut.jpg";
import accessibility from "/assets/images/accessibility.jpg";
import ringIcon from "/assets/images/icon-ring.png";
import focusIcon from "/assets/images/icon-focus.png";
import cameraIcon from "/assets/images/icon-camera.png";
import flashlightIcon from "/assets/images/icon-flashlight.png";
import voiceMemoIcon from "/assets/images/icon-voice-memo.png";
import translateIcon from "/assets/images/icon-translate.png";
import magnifierIcon from "/assets/images/icon-magnifier.png";
import shortcutIcon from "/assets/images/icon-shortcut.png";
import accessibilityIcon from "/assets/images/icon-accessibility.png";
import gradient from "/assets/images/gradient.png";
import usbc from "/assets/images/usbc.jpg";
import iphoneIcon from "/assets/images/icon-iphone.png";
import safety from "/assets/images/safety.jpg";
import values from "/assets/images/values.jpg";
import ios17ContactPoster from "/assets/images/ios17-contact-poster.jpg";
import ios17Namedrop from "/assets/images/ios17-namedrop.jpg";
import ios17LiveStickers from "/assets/images/ios17-live-stickers.jpg";
import mac from "/assets/images/mac.jpg";
import watch from "/assets/images/watch.jpg";
import airpods from "/assets/images/airpods.jpg";
import tradeIn from "/assets/images/icon-trade-in.png";
import appleCard from "/assets/images/icon-apple-card.png";
import carrierDeals from "/assets/images/icon-carrier-deals.png";
import delivery from "/assets/images/icon-delivery.png";
import specialistAlt from "/assets/images/icon-specialist-alt.png";
import personal from "/assets/images/icon-personal.png";
import shopping from "/assets/images/icon-shopping.png";
import iphone15Pro from "/assets/images/iphone-15pro.jpg";
import iphone15 from "/assets/images/iphone-15.jpg";
import a17 from "/assets/images/icon-a17.png";
import a16 from "/assets/images/icon-a16.png";
import camera3 from "/assets/images/icon-3camera.png";
import camera2 from "/assets/images/icon-2camera.png";
import battery from "/assets/images/icon-battery.png";
import swatchAllColors from "/assets/images/swatch-all-colors.jpg";
import allColors from "/assets/images/all-colors.jpg";
import naturalTitanium from "/assets/images/natural-titanium.jpg";
import blueTitanium from "/assets/images/blue-titanium.jpg";
import whiteTitanium from "/assets/images/white-titanium.jpg";
import blackTitanium from "/assets/images/black-titanium.jpg";

export const heroVideo = hmv;
export const smallHeroVideo = smallmv;
export const highlightFirstVideo = highlightFirstmv;
export const highlightSecondVideo = highlightSectmv;
export const highlightThirdVideo = highlightThirdmv;
export const highlightFourthVideo = highlightFourthmv;
export const exploreVideo = exploremv;
export const frameVideo = framemv;
export const telephotoVideo = telephotomv;
export const foundationVideo = foundation;

export const appleImg = apple;
export const searchImg = search;
export const bagImg = bag;
export const watchIconImg = watchIcon;
export const rightImg = right;
export const replayImg = replay;
export const playImg = play;
export const pauseImg = pause;
export const plusImg = plus;
export const arrowLeftImg = arrowLeft;
export const arrowRightImg = arrowRight;
export const arrowUpImg = arrowUp;
export const arrowDownImg = arrowDown;

export const yellowImg = yellow;
export const blueImg = blue;
export const whiteImg = white;
export const blackImg = black;
export const explore1Img = explore1;
export const explore2Img = explore2;
export const chipImg = chip;
export const frameImg = frame;
export const iguanaImg = iguana;
export const macroImg = macro;
export const mm13Img = mm13;
export const mm24Img = mm24;
export const mm28Img = mm28;
export const mm35Img = mm35;
export const mm48Img = mm48;
export const mm120Img = mm120;
export const phoneCameraImg = phoneCamera;
export const iphonBackgroundImg = iphonBackground;
export const silentImg = silent;
export const focusImg = focus;
export const cameraImg = camera;
export const flashlightImg = flashlight;
export const voiceMemoImg = voiceMemo;
export const translateImg = translate;
export const magnifierImg = magnifier;
export const shortcutImg = shortcut;
export const accessibilityImg = accessibility;
export const ringIconImg = ringIcon;
export const focusIconImg = focusIcon;
export const cameraIconImg = cameraIcon;
export const flashlightIconImg = flashlightIcon;
export const voiceMemoIconImg = voiceMemoIcon;
export const translateIconImg = translateIcon;
export const magnifierIconImg = magnifierIcon;
export const shortcutIconImg = shortcutIcon;
export const accessibilityIconImg = accessibilityIcon;
export const gradientImg = gradient;
export const usbcImg = usbc;
export const iphoneIconImg = iphoneIcon;
export const safetyImg = safety;
export const valuesImg = values;
export const ios17ContactPosterImg = ios17ContactPoster;
export const ios17NamedropImg = ios17Namedrop;
export const ios17LiveStickersImg = ios17LiveStickers;
export const macImg = mac;
export const watchImg = watch;
export const airpodsImg = airpods;
export const tradeInImg = tradeIn;
export const appleCardImg = appleCard;
export const carrierDealsImg = carrierDeals;
export const deliveryImg = delivery;
export const specialistAltImg = specialistAlt;
export const personalImg = personal;
export const shoppingImg = shopping;
export const iphone15ProImg = iphone15Pro;
export const iphone15Img = iphone15;
export const a17Img = a17;
export const a16Img = a16;
export const camera3Img = camera3;
export const camera2Img = camera2;
export const batteryImg = battery;
export const swatchAllColorsImg = swatchAllColors;
export const allColorsImg = allColors;
export const naturalTitaniumImg = naturalTitanium;
export const blueTitaniumImg = blueTitanium;
export const whiteTitaniumImg = whiteTitanium;
export const blackTitaniumImg = blackTitanium;
